---
title: "Raport_Wyniki"
output: html_document
---


```{r setup, include=FALSE}
require(tidyverse)
library(rhdf5)
library(factoextra)
library(NbClust)
library(e1071)
library(dbscan)
library(mclust)
library(DDoutlier)
library(dplyr)
library(plotly)
library(ROCR)
library(psych)
library(knitr)
library(data.table)
library(caTools)
library(partykit)
```

```{r load data}
rm(list = ls())
mammography_x = read.csv(file = 'mammography_x.csv', header=FALSE)
mammography_y = read.csv(file = 'mammography_y.csv', header=FALSE)
mammography = mammography_x %>% mutate(class = mammography_y$V1)

annthyroid_x = read.csv(file = 'annthyroid_x.csv', header=FALSE)
annthyroid_y = read.csv(file = 'annthyroid_y.csv', header=FALSE)
annthyroid = annthyroid_x %>% mutate(class = annthyroid_y$V1)
```


```{r echo=FALSE}
split_ratio = 0.8
set.seed(123)
split = sample.split(mammography, SplitRatio = split_ratio)
data_train = subset(mammography, split == TRUE)
data_test = subset(mammography, split == FALSE)

metric = "euclidean"
method = "kmeans"
dissimilarity_measure = "uCBLOF"
no_clusters = 3
algorithm = "Hartigan-Wong"
outlier_threshold = 0.8
source("Interface.R", local=knitr::knit_global(), echo=FALSE)
```



```{r echo=FALSE}
split_ratio = 0.8
set.seed(123)
split = sample.split(annthyroid, SplitRatio = split_ratio)
data_train = subset(annthyroid, split == TRUE)
data_test = subset(annthyroid, split == FALSE)

metric = "euclidean"
method = "kmeans"
dissimilarity_measure = "uCBLOF"
no_clusters = 5
algorithm = "Hartigan-Wong"
outlier_threshold = 0.3
source("Interface.R", local=knitr::knit_global(), echo=FALSE)
```
```{r echo=FALSE}
split_ratio = 0.8
set.seed(123)
split = sample.split(annthyroid, SplitRatio = split_ratio)
data_train = subset(annthyroid, split == TRUE)
data_test = subset(annthyroid, split == FALSE)

metric = "euclidean"
method = "kmeans"
dissimilarity_measure = "CBLOF"
no_clusters = 5
algorithm = "Hartigan-Wong"
outlier_threshold = 0.3
source("Interface.R", local=knitr::knit_global(), echo=FALSE)
```


```{r echo=FALSE}
split_ratio = 0.8
set.seed(123)
split = sample.split(annthyroid, SplitRatio = split_ratio)
data_train = subset(annthyroid, split == TRUE)
data_test = subset(annthyroid, split == FALSE)

metric = "euclidean"
method = "kmeans"
dissimilarity_measure = "LDCOF"
no_clusters = 5
algorithm = "Hartigan-Wong"
outlier_threshold = 0.3
source("Interface.R", local=knitr::knit_global(), echo=FALSE)
```
```{r echo=FALSE}
split_ratio = 0.8
set.seed(123)
split = sample.split(annthyroid, SplitRatio = split_ratio)
data_train = subset(annthyroid, split == TRUE)
data_test = subset(annthyroid, split == FALSE)

metric = "euclidean"
method = "cmeans"
dissimilarity_measure = "uCBLOF"
no_clusters = 5
algorithm = "Hartigan-Wong"
outlier_threshold = 0.3
source("Interface.R", local=knitr::knit_global(), echo=FALSE)
```
```{r echo=FALSE}
split_ratio = 0.8
set.seed(123)
split = sample.split(annthyroid, SplitRatio = split_ratio)
data_train = subset(annthyroid, split == TRUE)
data_test = subset(annthyroid, split == FALSE)

source("Classification.R", local=knitr::knit_global(), echo=FALSE)
```


